### ISSUE TITLE
README Suggestion

### ISSUE THREAD

**Issue by magicalyak** [denismakogon/ffmpeg-alpine#4]
At the end of the document there is a line for a sample Dockerfile
Shouldn't this line
`FROM denismakogon/ffmpeg-alpine:4.0-runtime as build-stage`
be
`FROM denismakogon/ffmpeg-alpine:4.0-buildstage as build-stage`
?

**Comment by denismakogon** [comment]
Oh, yeah, a huge typo! Please submit the PR, I'll update it right away.

**Comment by magicalyak** [comment]
Amazing work on this!  WIll do.

**Comment by denismakogon** [comment]
thanks.
